name: 'Trivy Security Scan'
description: 'Kjører Trivy på en container image og laster opp SARIF-resultater'

inputs:
  image:
    description: 'Container image som skal skannes'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Authenticate to access Docker image
      id: login
      uses: nais/login@v0
      with:
        team: toi

    - name: Eksporter image-verdi
      shell: bash
      run: echo "IMAGE=${{ inputs.image }}" >> "$GITHUB_ENV"

    - name: 'Defaulting to the tag "latest" of the Docker image to be scanned'
      if: inputs.image == '' && (contains(fromJSON('["refs/heads/master", "refs/heads/main"]'), github.ref))
      shell: bash
      run: |
        repo_name="${GITHUB_REPOSITORY/$GITHUB_REPOSITORY_OWNER}"
        repo_name="${repo_name#/}"
        repo_name="$(tr '[:upper:]' '[:lower:]' <<< "$repo_name")"
        registry="${{ steps.login.outputs.registry }}"
        registry="${registry%/}"
        IMAGE="${registry}/${repo_name}:latest"
        echo "IMAGE=${IMAGE}"
        echo "IMAGE=${IMAGE}" >> "$GITHUB_ENV"

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.34.0
      env:
        TRIVY_DB_REPOSITORY: 'public.ecr.aws/aquasecurity/trivy-db:latest'
        TRIVY_JAVA_DB_REPOSITORY: 'public.ecr.aws/aquasecurity/trivy-java-db:1'
      with:
        image-ref: ${{ env.IMAGE }}
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'HIGH,CRITICAL'
        limit-severities-for-sarif: true

    - name: Upload Trivy results to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
