on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
        description: "JDK version to be used on the Github workflow runner where the app is built. E.g. '17' or '21'"
    outputs:
      image:
        description: "Name of the built Docker image"
        value: ${{ jobs.build-and-publish.outputs.image }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker.outputs.image }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}
          cache: 'gradle'

      - run: ./gradlew build

      - uses: nais/docker-build-push@v0
        id: docker
        with:
          team: toi
          # The tag "latest" should only be applied to images based on the default branch
          tag: ${{ contains(fromJSON('["refs/heads/master", "refs/heads/main"]'), github.ref) && 'latest' || github.sha }}
          dockerfile: Dockerfile
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
