on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
        description: "JDK version to be used on the Github workflow runner where the app is built. E.g. '17' or '21'"
    outputs:
      image:
        description: "Name of the built Docker image"
        value: ${{ jobs.build-and-publish.outputs.image }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker.outputs.image }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false

      - uses: actions/setup-java@d7793b545071e98d581d3bf084a51c3213318a07 # v4.9.0
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}
          cache: 'gradle'

      - run: ./gradlew build

      - uses: nais/docker-build-push@31c3a7321909bcb20799fdf46153fec721fd9512 # v0
        id: docker
        with:
          team: toi
          tag: ${{ contains(fromJSON('["refs/heads/master", "refs/heads/main"]'), github.ref) && 'latest' || github.sha }}
          dockerfile: Dockerfile
