on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
        description: "E.g. '17' or '21'"

jobs:
  call-build-and-publish:
    uses: navikt/toi-github-actions-workflows/.github/workflows/build-java-gradlew.yaml@main
    with:
      java-version: '21'
    permissions:
      contents: read
      id-token: write
    secrets: inherit

  call-trivy-security-scan:
    needs: call-build-and-publish
    uses: navikt/toi-github-actions-workflows/.github/workflows/trivy-security-scan.yaml@main
    with:
      image: ${{ needs.call-build-and-publish.outputs.image }}
    permissions:
      id-token: write
      security-events: write
    secrets: inherit
