on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
        description: "E.g. '17' or '21'"
      baseimage-tagged-ref:
        required: true
        type: string
        description: "Full tagged reference to the runtime base image (registry/path:tag)"
      deploy-to-dev-if-branch-name-is:
        required: false
        type: string
jobs:
  call-build-java-gradlew:
    uses: navikt/toi-github-actions-workflows/.github/workflows/build-java-gradlew.yaml@autobump-docker-baseimage # zizmor: ignore[ref-confusion,unpinned-uses]
    with:
      java-version: ${{ inputs.java-version }}
      baseimage-tagged-ref: ${{ inputs.baseimage-tagged-ref }}
    permissions:
      contents: read
      id-token: write

  call-deploy:
    needs: call-build-java-gradlew
    uses: navikt/toi-github-actions-workflows/.github/workflows/deploy.yaml@autobump-docker-baseimage # zizmor: ignore[ref-confusion,unpinned-uses]
    with:
      image: ${{ needs.call-build-java-gradlew.outputs.image }}
      deploy-to-dev-if-branch-name-is: ${{ inputs.deploy-to-dev-if-branch-name-is }}
    permissions:
      contents: read
      id-token: write

  call-lagre-docker-baseimage-digest:
    needs: [call-build-java-gradlew, call-deploy]
    if: needs.call-deploy.outputs.deploy-to-prod-was-successful == 'true'
    uses: navikt/toi-github-actions-workflows/.github/workflows/lagre-docker-baseimage-digest.yaml@autobump-docker-baseimage # zizmor: ignore[ref-confusion,unpinned-uses]
    with:
      baseimage-tagged-ref: ${{ inputs.baseimage-tagged-ref }}
      baseimage-digest: ${{ needs.call-build-java-gradlew.outputs.baseimage-digest }}
    permissions: { }

  call-trivy-security-scan:
    needs: call-build-java-gradlew
    uses: navikt/toi-github-actions-workflows/.github/workflows/trivy-security-scan.yaml@v15 # zizmor: ignore[ref-confusion,unpinned-uses]
    with:
      image: ${{ needs.call-build-java-gradlew.outputs.image }}
    permissions:
      id-token: write
      security-events: write
