on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
        description: "E.g. '17' or '21'"
      deploy-to-dev-if-branch-name-is:
        required: false
        type: string
jobs:
  call-build-java-gradlew:
    uses: navikt/toi-github-actions-workflows/.github/workflows/build-java-gradlew.yaml@main
    with:
      java-version: ${{ inputs.java-version }}
    permissions:
      contents: read
      id-token: write
    secrets: inherit

  call-deploy:
    needs: call-build-java-gradlew
    uses: navikt/toi-github-actions-workflows/.github/workflows/deploy.yaml@main
    with:
      image: ${{ needs.call-build-java-gradlew.outputs.image }}
      deploy-to-dev-if-branch-name-is: ${{ inputs.deploy-to-dev-if-branch-name-is }}
    permissions:
      contents: read
      id-token: write
    secrets: inherit

  call-trivy-security-scan:
    needs: call-build-java-gradlew
    uses: navikt/toi-github-actions-workflows/.github/workflows/trivy-security-scan.yaml@main
    with:
      image: ${{ needs.call-build-java-gradlew.outputs.image }}
    permissions:
      id-token: write
      security-events: write
    secrets: inherit
