on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
        description: "Canonical reference to the built application image"
      deploy-to-dev-if-branch-name-is:
        required: false
        type: string
    outputs:
      deploy-to-prod-was-successful:
        description: Whether the production deployment completed successfully
        value: ${{ jobs.deploy-to-prod.outputs.deploy-to-prod-was-successful }}

jobs:
  deploy-to-dev:
    name: Deploy to dev
    if: github.ref == 'refs/heads/main' || github.ref == format('refs/heads/{0}', inputs.deploy-to-dev-if-branch-name-is)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/nais.yaml
          VAR: image=${{ inputs.image }}
          VARS: nais/dev-gcp.json

  deploy-to-prod:
    name: Deploy to prod
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/autobump-docker-baseimage' # TODO Are: Fjern andre ledd av if etter manuell testing
    needs: deploy-to-dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 15
    outputs:
      deploy-to-prod-was-successful: ${{ steps.mark-deployed.outputs.deploy-to-prod-was-successful }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/nais.yaml,nais/alerts.yaml
          VAR: image=${{ inputs.image }}
          VARS: nais/prod-gcp.json
      - name: Mark production deployment as successful
        id: mark-deployed
        run: echo "deploy-to-prod-was-successful=true" >> "$GITHUB_OUTPUT"
