on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
        description: "Canonical reference to the built application image"
      baseimage-tagged-ref:
        required: true
        type: string
        description: "Full tagged reference to the runtime base image (registry/path:tag)"
      baseimage-digest:
        required: true
        type: string
        description: "SHA-256 digest of the runtime base image used in the build"
      deploy-to-dev-if-branch-name-is:
        required: false
        type: string

jobs:
  deploy-to-dev:
    name: Deploy to dev
    if: github.ref == 'refs/heads/main' || github.ref == format('refs/heads/{0}', inputs.deploy-to-dev-if-branch-name-is)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/nais.yaml
          VAR: image=${{ inputs.image }}
          VARS: nais/dev-gcp.json

  deploy-to-prod:
    name: Deploy to prod
    if: github.ref == 'refs/heads/main'
    needs: deploy-to-dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/nais.yaml,nais/alerts.yaml
          VAR: image=${{ inputs.image }}
          VARS: nais/prod-gcp.json # TODO Hvorfor ble denne lagt til? Unødvendig?

  call-lagre-docker-baseimage-digest:
    needs: deploy-to-prod
    uses: navikt/toi-github-actions-workflows/.github/workflows/lagre-docker-baseimage-digest.yaml@autobump-docker-baseimage # zizmor: ignore[ref-confusion,unpinned-uses]
    with:
      baseimage-tagged-ref: ${{ inputs.baseimage-tagged-ref }}
      baseimage-digest: ${{ inputs.baseimage-digest }}
    permissions: {}
