on:
  workflow_call:
    inputs:
      image:
        required: false
        type: string

jobs:
  trivy-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to access Docker image
        id: login
        uses: nais/login@bb6c3e1e14e53d40d69d0d092bd2fce2e39ae3bf # v0
        with:
          team: toi

      - env:
          INPUT_IMAGE: ${{ inputs.image }}
        run: echo "IMAGE=${INPUT_IMAGE}" >> $GITHUB_ENV

      - name: 'Defaulting to the tag "latest" of the Docker image to be scanned'
        if: inputs.image == '' && (contains(fromJSON('["refs/heads/master", "refs/heads/main"]'), github.ref))
        env:
          REGISTRY: ${{ steps.login.outputs.registry }}
        run: |
          repo_name="${GITHUB_REPOSITORY/$GITHUB_REPOSITORY_OWNER}" # Remove owner name from repo name
          repo_name="${repo_name#/}" # Remove leading slash if it exists
          repo_name="$(tr '[:upper:]' '[:lower:]' <<< "$repo_name")" # To lower case
          registry="${REGISTRY%/}" # Trim trailing slash if it exists
          IMAGE="${registry}/${repo_name}:latest"
          echo "IMAGE=${IMAGE}" # Print to log
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        env:
          TRIVY_DB_REPOSITORY: 'public.ecr.aws/aquasecurity/trivy-db:latest' # Workaround until this issue is resolved: https://github.com/aquasecurity/trivy-action/issues/389
          TRIVY_JAVA_DB_REPOSITORY: 'public.ecr.aws/aquasecurity/trivy-java-db:1' # Workaround until this issue is resolved: https://github.com/aquasecurity/trivy-action/issues/389
        with:
          image-ref: ${{ env.IMAGE }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'
          limit-severities-for-sarif: true

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@5595ccaf912efad79be6eef63a5619ff05969be3 # v4.37.6
        with:
          sarif_file: 'trivy-results.sarif'
