name: 'Deployment Oppsummering (suksess)'
description: 'Legger til en suksessmelding i GITHUB_STEP_SUMMARY'

inputs:
  image:
    description: 'Image som ble deployet'
    required: true
  branch:
    description: 'Branchnavn'
    required: true
  commit:
    description: 'Commit SHA'
    required: true
  environment:
    description: 'Miljø som ble deployet til'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Suksessoppsummering
      shell: bash
      run: |
        echo "## Deployment Fullført! 🎉" >> "$GITHUB_STEP_SUMMARY"
        echo "* Image: \`${{ inputs.image }}\`" >> "$GITHUB_STEP_SUMMARY"
        echo "* Branch: \`${{ inputs.branch }}\`" >> "$GITHUB_STEP_SUMMARY"
        echo "* Commit: \`${{ inputs.commit }}\`" >> "$GITHUB_STEP_SUMMARY"
        echo "* Miljø: ${{ inputs.environment }}" >> "$GITHUB_STEP_SUMMARY"
